"""empty message

Revision ID: f0254c87b48c
Revises: 55a33e52d5a1
Create Date: 2024-03-01 01:06:05.736417

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f0254c87b48c"
down_revision: Union[str, None] = "55a33e52d5a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("author", sa.Column("plane_busyness", sa.Float(), nullable=True))
    op.add_column("author", sa.Column("busyness", sa.Float(), nullable=True))
    op.drop_column("author", "bussynes")
    op.drop_column("author", "plane_bussyness")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("author", sa.Column("plane_bussyness", mysql.FLOAT(), nullable=True))
    op.add_column("author", sa.Column("bussynes", mysql.FLOAT(), nullable=True))
    op.drop_column("author", "busyness")
    op.drop_column("author", "plane_busyness")
    # ### end Alembic commands ###
