"""Changed string to date deadline field

Revision ID: e6732d1cfa72
Revises: 6f87455b0c70
Create Date: 2024-04-12 23:08:58.145198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6732d1cfa72'
down_revision: Union[str, None] = '6f87455b0c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'real_deadline',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'real_deadline',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
