"""empty message

Revision ID: 6f87455b0c70
Revises: d30bfcf717f6
Create Date: 2024-03-11 04:47:43.787170

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f87455b0c70"
down_revision: Union[str, None] = "d30bfcf717f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lead", sa.Column("alert_comment", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lead", "alert_comment")
    # ### end Alembic commands ###
