"""Changed uniqueness from varchar to Text

Revision ID: 780b1ff977b3
Revises: 5f9c73c2e995
Create Date: 2024-05-06 03:40:59.477446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "780b1ff977b3"
down_revision: Union[str, None] = "5f9c73c2e995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lead", "uniqueness", existing_type=mysql.VARCHAR(length=256), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lead", "uniqueness", existing_type=sa.Text(), type_=mysql.VARCHAR(length=256), existing_nullable=True
    )
    # ### end Alembic commands ###
