"""Added ready date to lead model

Revision ID: 5f9c73c2e995
Revises: 8ec091a8eb0f
Create Date: 2024-04-15 09:59:57.328343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9c73c2e995'
down_revision: Union[str, None] = '8ec091a8eb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
