"""empty message

Revision ID: 683a06d90625
Revises: f0254c87b48c
Create Date: 2024-03-01 01:13:35.220193

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "683a06d90625"
down_revision: Union[str, None] = "f0254c87b48c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("author", sa.Column("rating", sa.Integer(), nullable=True))
    op.drop_column("author", "raiting")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("author", sa.Column("raiting", mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("author", "rating")
    # ### end Alembic commands ###
