"""empty message

Revision ID: 3dc0d0126585
Revises: 
Create Date: 2024-02-19 22:10:44.637063

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dc0d0126585"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=True),
        sa.Column("raiting", sa.Float(), nullable=True),
        sa.Column("bussyness", sa.Float(), nullable=True),
        sa.Column("card_number", sa.String(length=256), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lead_status",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lead",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=True),
        sa.Column("author_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["lead_status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_author_id"), "lead", ["author_id"], unique=False)
    op.create_index(op.f("ix_lead_status_id"), "lead", ["status_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lead_status_id"), table_name="lead")
    op.drop_index(op.f("ix_lead_author_id"), table_name="lead")
    op.drop_table("lead")
    op.drop_table("lead_status")
    op.drop_table("author")
    # ### end Alembic commands ###
